name: farmers
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: iterative/setup-dvc@v1
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 
          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add figure to the report
          echo "## Validating results by region"
          cml send-comment report.md
          
          echo "## End"
        
